### PR TITLE
cmake: Look for CLANG_INCLUDE_DIRS

### PR DESCRIPTION
**Pull request by teto**
Recent clang versions define in lib/cmake/ some cmake files that can set
the CLANG_INCLUDE_DIRS.

In fact we don't need to look for LLVM, we should first look for clang and if it's not found fallback on LLVM.

### CODE REVIEW

**Comment by bradking** [comment]
@teto thanks.  Finding the `Clang` package is complicated by the fact that it must match the `LLVM` package version.  I opened #100 for finding the Clang CMake package, and fixed it with 90d4abc1b5035e669df9e82038ee252ff34a3a45.  The rest of your changes can be rebased on `master`.

**Comment by bradking** [comment]
@teto I updated your branch to rebase on `master` and revise the approach and the commit message.  Please fetch, reset your checkout, and try it out.

**Comment by teto** [comment]
Thanks for the changes, sorry I haven't tested them yet but the project I want to test it on has some weird problems that I have to fix before I can try castXML.

**Comment by LeonardKoenig** [comment]
I didn't have a problem building before, but now I get this error:

```
[...]
-- Found Git: /bin/git (found version "2.16.0") 
CMake Error at CMakeLists.txt:118 (message):
  LLVM_DIR refers to a LLVM installation:

    //lib/cmake/llvm

  that does not have `clang/` headers in any include directory:

    //include



-- Configuring incomplete, errors occurred!
```

Log is attached. It seems that it thinks it found a valid installation, despite it hasn't.

I'm on ArchLinux, tried cloning and installing via AUR.

[CMakeOutput.log](https://github.com/CastXML/CastXML/files/1652081/CMakeOutput.log)

**Comment by bradking** [comment]
@LeonardKoenig please open a separate issue for that.  Also, I've just pushed some updates that should improve the error message.

**Comment by bradking** [comment]
@LeonardKoenig actually I think this PR fixes exactly the issue you see.  I've just rebased @teto's branch here on `master` again.  Please fetch it to try out.

**Comment by teto** [comment]
actually nixpkgs introduced a package libclang precisely to address this kind of scenario so I need to retry.

**Comment by LeonardKoenig** [comment]
I just tried that code but it still doesn't work, but I suppose it's actually a LLVM bug because even with simple `find_package` calls to Clang and LLVM which should work on a modern installation, `LLVM_INCLUDE_DIRS` (and also `CLANG_INCLUDE_DIRS`) only includes `//include` for me, but these are set by `LLVMConfig.cmake` using this code:

```CMake
get_filename_component(LLVM_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(LLVM_INSTALL_PREFIX "${LLVM_INSTALL_PREFIX}" PATH)
get_filename_component(LLVM_INSTALL_PREFIX "${LLVM_INSTALL_PREFIX}" PATH)
get_filename_component(LLVM_INSTALL_PREFIX "${LLVM_INSTALL_PREFIX}" PATH)
```

The number of calls to `get_filename_component` are calculated at compile time but this seems to going wrong.

Anyway, using `-DClang_DIR` and the hinting macros it "works".

**Comment by bradking** [comment]
@LeonardKoenig thanks.  I think the point of this issue/PR is that Clang and LLVM can be installed separately instead of in the same prefix.  If that is the case for you then a separate `Clang_DIR` and `LLVM_DIR` may be needed to build.

I've also seen distro packaging break the relative path computation you quoted by moving files within the packages to a layout different than the upstream `make install` would do, or by adding symlinks.

**Comment by teto** [comment]
Finally had a chance to test and it worked. I add to use both 
```
llvmPackages.clang-unwrapped
llvmPackages.llvm
```
as build inputs to the nix package since the clang cmake file must find LLVM as well.

The content of /nix/store/wzd2k2ax5kbsi0sn3c1hbk4i6qgsi8rw-clang-5.0.1/lib/cmake/clang/ClangConfig.cmake just for info:
```
# This file allows users to call find_package(Clang) and pick up our targets.


# Compute the installation prefix from this LLVMConfig.cmake file location.
get_filename_component(CLANG_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(CLANG_INSTALL_PREFIX "${CLANG_INSTALL_PREFIX}" PATH)
get_filename_component(CLANG_INSTALL_PREFIX "${CLANG_INSTALL_PREFIX}" PATH)
get_filename_component(CLANG_INSTALL_PREFIX "${CLANG_INSTALL_PREFIX}" PATH)

find_package(LLVM REQUIRED CONFIG
             HINTS "${CLANG_INSTALL_PREFIX}/lib/cmake/llvm")

set(CLANG_EXPORTED_TARGETS "blabla....")
set(CLANG_CMAKE_DIR "${CLANG_INSTALL_PREFIX}/lib/cmake/clang")
set(CLANG_INCLUDE_DIRS "${CLANG_INSTALL_PREFIX}/include")

# Provide all our library targets to users.
include("${CLANG_CMAKE_DIR}/ClangTargets.cmake")

```

**Comment by bradking** [comment]
@teto thanks!

**Comment by teto** [comment]
I was going to bump the PR :D thanks !

**Pull request merged**
