### PR TITLE
DllExport and DLLImport attribute support

### PR DESCRIPTION
**Pull request by MarkARussell**
Added support for including a "dllexport" and "dllimport" attribute for a clang::Decl.  Based on the presence of the corresponding clang attributes DLLExportAttr and DLLImportAttr.

Request includes the changes to the outputter, as well as unit tests.  Note that I based all the unit tests off of the annotate tests (created a copy), and only skipped those annotate tests that were not applicable for dllexport/dllimport.  All tests passing at time of creation.

### CODE REVIEW

**Comment by bradking** [comment]
Thanks!   This is a great start.

Unfortunately the new tests all fail on non-Windows target platforms because the declspec markup is not recognized by Clang.  See `test/CMakeLists.txt`'s block using `LLVM_TARGETS_TO_BUILD` in its condition.  You could add tests with a similar condition so that an explicit `-target` can be used.

**Comment by MarkARussell** [comment]
I've clearly spent too much time in Windows only environments :-)

I can certainly move the new tests into a new if block, but what would I be testing against?  Would it be another test against LLVM_TARGETS_TO_BUILD with a different match or would I be testing against some other variable?  Also what would I match against?

Alternatively, could the new tests simply be moved into the existing if block matching X86?  It looks like the contents of that block are already msvc specific, though x86 only (no x64, not that this should matter for the declspec tests).

Forgive my lack of cmake knowledge.  It's rather new to me.

Thanks,
Mark


On Sep 05, 2017, at 05:04 AM, Brad King <notifications@github.com> wrote:

Thanks! This is a great start.
Unfortunately the new tests all fail on non-Windows target platforms because the declspec markup is not recognized by Clang. See test/CMakeLists.txt's block using LLVM_TARGETS_TO_BUILD in its condition. You could add tests with a similar condition so that an explicit -target can be used.

**Comment by bradking** [comment]
@MarkARussell the purpose of checking `LLVM_TARGETS_TO_BUILD` is just to make sure that a target is supported so that we can add tests that use a specific `-target` for msvc (which works in Clang even on Linux).  Adding these to the existing x86 block would be fine.

**Comment by MarkARussell** [comment]
Updated the branch to move the tests into the existing LLVM_TARGETS_TO_BUILD if block in test/CMakeLists.txt where the other msvc specific tests already were.  Additionally I updated all the input/expect test files specific to the dllexport/dllimport tests to include the "-ms" moniker that is being used for other msvc specific tests.

Verified everything compiles and tests all run (and pass) on both Windows 10 and MacOS 10.12

**Comment by bradking** [comment]
Thanks.  The tests pass for me on Linux now too, thanks to the `-target` option now used.

Please squash this all down into one commit.  Adding this feature and its tests is one logical step in functionality.  Use a subject line like `Output: Add dllexport/dllimport attributes`.

Also please update `ASTVisitor::OutputStartXMLTags` to bump the castxml output version to `1.1.1` and the `cvs_revision` to `1.141`.  That way clients will be able to know that the new information is available.

**Pull request merged**
