### PR TITLE
Allow warnings about unknown float abi during tests

### PR DESCRIPTION
**Pull request by ellert**
This makes the tests succeed on arm.

### CODE REVIEW

**Comment by bradking** [comment]
Thanks.  In order to make sure we only remove an entire line and not part of one, please try:

    string(REGEX REPLACE "(^|\n)warning: unknown platform, assuming -mfloat-abi=soft\n" "\\1" actual_std${o} "${actual_std${o}}")

OTOH, why does this warning appear in the first place?  Should we be passing an extra flag on this architecture?

**Comment by ellert** [comment]
Pull request updated as requested (minus the extra "std" in the variable name, which seems to be some c&p error).

You could instead add -mfloat-abi=soft to the castxml runs in the test, but you can't blindly add it to all, since then some of the tests fails with other errors such as:

error: no input files
warning: argument unused during compilation: '-mfloat-abi=soft'

So there would have to be some way to say which tests should have the flag and which not.

**Comment by bradking** [comment]
Thanks for the update.  I'd like to understand more about this `-mfloat-abi=soft` flag though.

* When one compiles using Clang on this architecture does it produce this warning too?  On what code?
* In which tests does the warning appear in CastXML?

**Comment by ellert** [comment]
13% tests passed, 325 tests failed out of 375

For full log see:
https://kojipkgs.fedoraproject.org/work/tasks/4370/11194370/build.log

**Comment by bradking** [comment]
Thanks.  I've applied your changes as commit 552dd691215cdafdbe6706e6f76be9d392fb3ffe.

For reference, I can reproduce the warning by running Clang with `-target armv7hl-linux-gnu` locally.

**Pull request closed without merging**
