### PR TITLE
New CastXML file format

### PR DESCRIPTION
**Pull request by iMichka**
These first commits introduce the new --castxml-output=1 flag, which is discussed in #72.

The tests have been adapted and all pass (1701 tests on my mac).

@bradking This is a first bunch of commits to see if this goes in the right direction.
One concern I have is the versioning system: at what rate do we plan to introduce new file format versions? With the old system we just updated the version number in the XML file. Here, for each format breaking change, we will need to introduce a number, that the user can freely set over the command line. This means duplicating the tests each time.

I guess the goal is to allow the decoupling of "maintenance" updates (for infrastructure reasons like llvm version bumps) from the xml format update; in the past if you used a newer version of gccxml, this also implied a xml format bump, which was maybe not wanted. I am afraid that this will add a great burden to the project.

Of course if we say that version 1 is to be in "beta" state for the next 1-2 years, until it stabilises, I am ok with that. Moving to version 2 for whatever reason is unlikely to happen.

Tell me if this already looks OK for you. I will probably add the elaborated types commit on top of this Pull Request, so that we have a first practical example for all these changes.

### CODE REVIEW

**Comment by bradking** [comment]
Thanks!  Looks good so far.

> concern I have is the versioning system

Yes, we should make sure we have a plan for that.  I had envisioned the version number on the `--castxml-output=` flag to be changed *very* rarely, and that incrementing it would be akin to the `GCC_XML => CastXML` change.  I think within version `1` we should still have a version scheme similar to what `cvs_revision` was in `GCC_XML`.  Previously we've had

```xml
<GCC_XML version="0.9.0" cvs_revision="1.139">...</GCC_XML>
```

where `version=` is the version of gccxml and `cvs_revision=` is the granular format version.

I think we should now have

```xml
<CastXML version="0.1-g2487703" format="1.2.3">...</GCC_XML>
```

where `version=` is still the version of CastXML that wrote the file (so that clients can adapt to bugs known in that version and such).  Then `format=` version components can be something like:

* The first component is the "epic" version number given to `--castxml-output=` and will always be `1` for now.
* The second component is the "major" version number and increments whenever we add a new XML element or make a change like when we made some names fully qualified.  Clients will need some updating.
* The third component is the "minor" version number and increments whenever we add a new XML attribute to an existing element or fix a bug in the output of an existing element or attribute (clients should work unchanged unless they want the new info).

**Comment by iMichka** [comment]
I'm ok with the format attribute, but I'm not really happy with the ```version=```

If that is the short git sha1, it needs to be modified
- each time we make a commit
- it's not really useful for version comparisons

**Comment by bradking** [comment]
The value of `version=` is already computed by the build system.  It is CastXML's version number in `<major>.<minor>`form followed optionally by `-g...` for the specific Git sha1.  OTOH I guess the format version number gives clients all the information they need, so let's drop `version=` for now.

**Comment by bradking** [comment]
@iMichka thanks for the update.  Is this still a WIP or do you intend to get this merged as-is and then base the actual format changes on it as a separate PR?

**Comment by iMichka** [comment]
I updated the title. I think this is ready to go and could be merged. It's probably more efficient if you want to do some changes on top of this pull request, there may be some typos that slipped through, or some details that I have forgotten.

This leaves me some time to prepare the changes for the elaborated types in a separate pull request. It's almost ready but I will need a day or two. And there may be some discussion about the implementation that we need to discuss, though I think I found an elegant way to handle that new case/

**Comment by bradking** [comment]
@iMichka I updated your branch with a revised history and a few minor tweaks.  Please check it and then I'll merge this.

**Comment by iMichka** [comment]
Looks good to me, this can be merged now. Thanks for the cleanup.

**Pull request merged**
